[localhost] ~/programming_elixiir/work/17/sequence % iex -S mix
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Compiling 1 file (.ex)
Sequence.Stack.Server
---復活---
Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>  Sequence.Stack.Server.inspect
:ok
iex(2)> [1, 2, 3, 4, 5]
iex(2)>  Sequence.Stack.Server.pop
1
iex(3)>  Sequence.Stack.Server.pop
2
iex(4)>  Sequence.Stack.Server.pop
3
iex(5)>  Sequence.Stack.Server.pop
4
iex(6)>  Sequence.Stack.Server.pop
5
iex(7)>  Sequence.Stack.Server.pop
ウワーッ 死にます これから
{{:badmatch, []},
 [
   {Sequence.Stack.Server, :handle_call, 3,
    [file: 'lib/stack/server.ex', line: 31]},
   {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 715]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 744]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
 ]}
[]

18:25:16.163 [error] GenServer Sequence.Stack.Server terminating
** (MatchError) no match of right hand side value: []
    (sequence 0.1.0) lib/stack/server.ex:31: Sequence.Stack.Server.handle_call/3
    (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
    (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.158.0>): :pop
State: []
Client #PID<0.158.0> is alive

    (stdlib 3.14) gen.erl:208: :gen.do_call/4
    (elixir 1.11.3) lib/gen_server.ex:1024: GenServer.call/3
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.3) src/elixir.erl:280: :elixir.recur_eval/3
    (elixir 1.11.3) src/elixir.erl:265: :elixir.eval_forms/3
    (iex 1.11.3) lib/iex/evaluator.ex:261: IEx.Evaluator.handle_eval/5
    (iex 1.11.3) lib/iex/evaluator.ex:242: IEx.Evaluator.do_eval/3
    (iex 1.11.3) lib/iex/evaluator.ex:220: IEx.Evaluator.eval/3
Sequence.Stack.Server
---復活---
** (exit) exited in: GenServer.call(Sequence.Stack.Server, :pop, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: []
            (sequence 0.1.0) lib/stack/server.ex:31: Sequence.Stack.Server.handle_call/3
            (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
            (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    (elixir 1.11.3) lib/gen_server.ex:1027: GenServer.call/3
iex(7)>